name: weekly-run

on:
  # schedule:
    # - cron: '*/5 * * * *'
    # - cron: '5 8 * * 0'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
          cache: 'pip'
      - name: Install necessary libraries
        run: |
          python -m pip install --upgrade pip    
          pip install -r requirements.txt
      - name: Execute Python Script
        # env:
        #   URI: ${{ secrets.URI }}
        run: python train.py
      - name: Commit files
        id: commit
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "github-actions"
          git add --all
          if [-z "$(git status --porcelain)"]; then
            echo "::set-output name=push::false"
          else
            git commit -m "Add changes" -a
            echo "::set-output name=push::true"
          fi
        shell: bash
      - name: Push changes
        if: steps.commit.outputs.push == 'true'
        uses: ad-m/github-push-action@master
        with:
          github_token: "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"
