[theme]

# Primary accent for interactive elements
primaryColor = '#00C957'

# Background color for the main content area
backgroundColor = '#F8F8F8'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#7FFFD4'

# Color used for almost all text
textColor = 'black'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace)
# Default: "sans serif"
font = "sans serif"